version: "{build}"

image: Visual Studio 2019

skip_tags: true
clone_depth: 1

configuration: Release
platform: Any CPU

before_build:
  - nuget restore

build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
