version: '{build}'

image: Visual Studio 2017

branches:
  only:
  - master
  - develop

skip_tags: true
clone_depth: 1

configuration: Release
platform: Any CPU

before_build:
- cmd: '".nuget/NuGet.exe" restore Simplify.Web.Multipart.sln'

build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
