<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;netstandard2.1</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<Version>1.9</Version>

		<Authors>Simplify community</Authors>
		<Product>Simplify</Product>
		<Description>Simplify.Web multipart form model binder</Description>
		<Copyright>Licensed under LGPL</Copyright>
		<PackageProjectUrl>https://github.com/SimplifyNet/Simplify.Web.Multipart</PackageProjectUrl>
		<RepositoryUrl>https://github.com/SimplifyNet/Simplify.Web.Multipart</RepositoryUrl>
		<RepositoryType>GIT</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>Simplify.Web multipart</PackageTags>

		<PackageIcon>icon.png</PackageIcon>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>

		<PackageReleaseNotes>See https://github.com/SimplifyNet/Simplify.Web.Multipart/tree/master/src/Simplify.Web.Multipart/CHANGELOG.md for details</PackageReleaseNotes>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Simplify.Web" Version="5.3.0" />
		<PackageReference Include="HttpMultipartParser" Version="10.0.0" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\..\images\icon.png" Pack="true" Visible="false" PackagePath="" />
		<None Include="..\..\LICENSE.txt" Pack="true" PackagePath="\" />
		<None Include="CHANGELOG.md" Pack="true" PackagePath="\" />
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>